In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
import zipfile
import os

zip_path = "/content/archive (7).zip"
extract_path = "/content/movielens_data"

# Folder create karo agar nahi hai
os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Unzipped successfully!")

Unzipped successfully!

In [4]:
import os
print(os.listdir("/content/movielens_data"))

['links.csv', 'README.txt', 'tags.csv', 'ratings.csv', 'movies.csv']

In [5]:
import pandas as pd

movies = pd.read_csv("/content/movielens_data/movies.csv")
ratings = pd.read_csv("/content/movielens_data/ratings.csv")

movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [6]:
movies['genres'] = movies['genres'].str.replace('|', ' ')

In [7]:
tfidf = TfidfVectorizer(stop_words='english')

tfidf_matrix = tfidf.fit_transform(movies['genres'])

tfidf_matrix.shape

(9125, 23)

In [8]:
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

cosine_sim

array([[1.        , 0.80403568, 0.15641664, ..., 0.        , 0.26646851,
        0.        ],
       [0.80403568, 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.15641664, 0.        , 1.        , ..., 0.        , 0.58699859,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        1.        ],
       [0.26646851, 0.        , 0.58699859, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        1.        ]])

In [9]:
indices = pd.Series(movies.index, index=movies['title']).drop_duplicates()

indices.head()

title
Toy Story (1995)                      0
Jumanji (1995)                        1
Grumpier Old Men (1995)               2
Waiting to Exhale (1995)              3
Father of the Bride Part II (1995)    4
dtype: int64

In [10]:
def recommend_movies(title, cosine_sim=cosine_sim):

    idx = indices[title]

    sim_scores = list(enumerate(cosine_sim[idx]))

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:6]

    movie_indices = [i[0] for i in sim_scores]

    return movies['title'].iloc[movie_indices]

In [11]:
recommend_movies("Toy Story (1995)")

1815                                       Antz (1998)
2506                                Toy Story 2 (1999)
3003    Adventures of Rocky and Bullwinkle, The (2000)
3217                  Emperor's New Groove, The (2000)
3805                             Monsters, Inc. (2001)
Name: title, dtype: object